"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RefreshTokenRepository = exports.OpinionRepository = exports.CommentRepository = exports.PostRepository = exports.TagRepository = exports.StatsRepository = exports.AuthRepository = exports.UserRepository = void 0;
var user_repository_1 = require("./user.repository");
Object.defineProperty(exports, "UserRepository", { enumerable: true, get: function () { return user_repository_1.default; } });
var auth_repository_1 = require("./auth.repository");
Object.defineProperty(exports, "AuthRepository", { enumerable: true, get: function () { return auth_repository_1.default; } });
var stats_repository_1 = require("./stats.repository");
Object.defineProperty(exports, "StatsRepository", { enumerable: true, get: function () { return stats_repository_1.default; } });
var tag_repository_1 = require("./tag.repository");
Object.defineProperty(exports, "TagRepository", { enumerable: true, get: function () { return tag_repository_1.default; } });
var post_repository_1 = require("./post.repository");
Object.defineProperty(exports, "PostRepository", { enumerable: true, get: function () { return post_repository_1.default; } });
var comment_repository_1 = require("./comment.repository");
Object.defineProperty(exports, "CommentRepository", { enumerable: true, get: function () { return comment_repository_1.default; } });
var opinion_repository_1 = require("./opinion.repository");
Object.defineProperty(exports, "OpinionRepository", { enumerable: true, get: function () { return opinion_repository_1.default; } });
var refresh_token_repository_1 = require("./refresh.token.repository");
Object.defineProperty(exports, "RefreshTokenRepository", { enumerable: true, get: function () { return refresh_token_repository_1.default; } });
