"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RefreshToken = exports.Opinion = exports.Comment = exports.Post = exports.Tag = exports.Auth = exports.User = void 0;
var user_model_1 = require("./user.model");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_model_1.default; } });
var auth_model_1 = require("./auth.model");
Object.defineProperty(exports, "Auth", { enumerable: true, get: function () { return auth_model_1.default; } });
var tag_model_1 = require("./tag.model");
Object.defineProperty(exports, "Tag", { enumerable: true, get: function () { return tag_model_1.default; } });
var post_model_1 = require("./post.model");
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return post_model_1.default; } });
var comment_model_1 = require("./comment.model");
Object.defineProperty(exports, "Comment", { enumerable: true, get: function () { return comment_model_1.default; } });
var opinion_model_1 = require("./opinion.model");
Object.defineProperty(exports, "Opinion", { enumerable: true, get: function () { return opinion_model_1.default; } });
var refresh_token_model_1 = require("./refresh.token.model");
Object.defineProperty(exports, "RefreshToken", { enumerable: true, get: function () { return refresh_token_model_1.default; } });
