"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostRoutes = exports.TagRoutes = exports.UserRoutes = exports.AuthRoutes = void 0;
var auth_routes_1 = require("./auth.routes");
Object.defineProperty(exports, "AuthRoutes", { enumerable: true, get: function () { return auth_routes_1.default; } });
var user_routes_1 = require("./user.routes");
Object.defineProperty(exports, "UserRoutes", { enumerable: true, get: function () { return user_routes_1.default; } });
var tag_routes_1 = require("./tag.routes");
Object.defineProperty(exports, "TagRoutes", { enumerable: true, get: function () { return tag_routes_1.default; } });
var post_routes_1 = require("./post.routes");
Object.defineProperty(exports, "PostRoutes", { enumerable: true, get: function () { return post_routes_1.default; } });
