"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const nk_node_library_1 = require("nk-node-library");
const controllers_1 = require("../controllers");
const router = express_1.Router();
const controller = new controllers_1.TagController();
router.post('/search', nk_node_library_1.Middlewares.authCheck(false), controller.getAll);
router.get('/:id', nk_node_library_1.Middlewares.authCheck(false), controller.get);
exports.default = router;
