"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const nk_js_library_1 = require("nk-js-library");
const nk_node_library_1 = require("nk-node-library");
const services_1 = require("../services");
const app = express();
app.use(cors());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(nk_node_library_1.Middlewares.logger('v1'));
app.use(nk_node_library_1.Middlewares.requestProcessor(services_1.RefreshTokenService));
nk_js_library_1.Utils.GoogleGeocoderUtils.loadAPI('AIzaSyDl4dmvk0tBIX0-BWCaOZy0MjAcTtLHo60');
nk_js_library_1.Utils.MailerUtils.loadMailerAPI('starlight.mailer.service@gmail.com', 'Mailer@Starlight*com');
exports.default = app;
